(function(w){function K(){}function s(a){return null==a?String(a):"object"===typeof a||"function"===typeof a?ga[ha.call(a)]||"object":typeof a}function ia(a){return Aa.test(ha.call(a))}function L(){return"avalon"+Math.random().toString(36).substring(2,15)+Math.random().toString(36).substring(2,15)}function D(a,b){if(a){var d;var c=a.length;d=s(a);d=avalon.isWindow(a)?!1:1===a.nodeType&&c?!0:"array"===d||"function"!==d&&(0===c||"number"===typeof c&&0<c&&c-1 in a);c=0;if(d)for(d=a.length;c<d;c++)b(c,
a[c]);else for(c in a)a.hasOwnProperty(c)&&b(c,a[c])}}function ja(){if(E){for(var a=0,b;b=E[a++];)b();E=null}}function ka(a){return a.replace(/([a-z\d])([A-Z]+)/g,"$1-$2").toLowerCase()}function M(a){return 0>a.indexOf("-")&&0>a.indexOf("_")?a:a.replace(/[-_][^-_]/g,function(a){return a.charAt(1).toUpperCase()})}function la(a){var b=!1;if(Ba.test(a)||+a+""===a)b=!0;try{return b?eval("0,"+a):a}catch(d){return a}}function F(a,b,d){a="for(var "+a+"i=0,n = this.length; i < n; i++){"+b.replace("_","((i in this) && fn.call(scope,this[i],i,this))")+
"}"+d;return Function("fn,scope",a)}function T(a,b,d){if(d){var c=a.length;d=b.length;c>d?a.splice(d,c-d):d>c&&a.push.apply(a,b.slice(c));d=Math.min(c,d);for(c=0;c<d;c++)a.set(c,b[c])}else for(c in b)b.hasOwnProperty(c)&&(a.hasOwnProperty(c)&&"$id"!==c)&&(a[c]=b[c])}function G(a,b,d){if(d)return ma(a);var c=a.$skipArray,e={},f={},g=[],h=[],k=Object.keys(U);b=b||{};c=Array.isArray(c)?c.concat(k):k;D(a,function(a,d){U[a]||(b[a]=d);var x=s(d);if("function"===x)k.push(a);else{if(-1!==c.indexOf(a)||"$"===
a.charAt(0)&&!Ca[a])return k.push(a);var p,na;if("object"===x&&"function"===typeof d.get&&2>=Object.keys(d).length){var m=d.set,n=d.get;p=function(c){if(arguments.length)N||("function"===typeof m&&m.call(e,c),na!==c&&(na=c,z(p),e.$events&&e.$fire(a,c,d)));else return(V||!p.locked)&&oa(p),d=b[a]=n.call(e)};p.nick=a;h.push(p)}else d=NaN,g.push(a),p=function(c){if(arguments.length){if(!N&&d!==c){var f=d;"array"===x||"object"===x?d&&d.$id?T(d,c,Array.isArray(c)):d=Array.isArray(c)?ma(c,e,a):G(c,c):d=
c;b[a]=d&&d.$id?d.$model:d;z(p);e.$events&&e.$fire(a,d,f)}}else return oa(p),d};p[A]=[];f[a]={set:p,get:p,enumerable:!0}}});e=O(e,f,k);k.forEach(function(b){U[b]||(e[b]=a[b])});g.forEach(function(b){e[b]=a[b]});h.forEach(function(a){r[n]=a;g=e[a.nick];a.locked=1;delete r[n]});e.$json=b;e.$model=b;e.$events={};e.$watch=W.$watch.bind(e);e.$unwatch=W.$unwatch.bind(e);e.$fire=W.$fire.bind(e);e.$id=L();e.hasOwnProperty=function(a){return a in e.$model};return e}function oa(a){r[n]&&(a=a[A])&&avalon.Array.ensure(a,
r[n])}function z(a,b){var d=a[A];if(d&&d.length)for(var c=[].slice.call(arguments,1),e=d.concat(),f=0,g;g=e[f++];)(b=g.element)&&!b.noRemove&&(0===b.sourceIndex||null===b.parentNode)?(avalon.Array.remove(d,g),avalon.log(g+"")):g.apply(0,c)}function X(a,b){b=b||[];var d=a.getAttribute(t+"skip"),c=a.getAttribute(t+"important"),e=a.getAttribute(t+"controller");if("string"!==typeof d){if(c)if(avalon.models[c])b=[avalon.models[c]],a.removeAttribute(t+"important");else return;else if(e){d=avalon.models[e];
if(!d)return;b=[d].concat(b);a.removeAttribute(t+"controller")}for(var d=b,c=[],e=0,f;f=a.attributes[e++];)if(f.specified){var g=!1;if(-1!==f.name.indexOf(t)){var h=f.name.replace(t,"");if(0<h.indexOf("-"))var k=h.split("-"),h=k.shift();g="function"===typeof q[h]}else/\{\{[^}]*\}\}/.test(f.value)&&(h=g="attr");g&&c.push({type:h,args:k||[],element:a,remove:!0,node:f,value:f.nodeValue})}Y(c,d);if(!Da[a.tagName]&&Ea.test(a.innerHTML)){h=[];c=a.childNodes;for(k=0;d=c[k++];)1===d.nodeType?X(d,b):3===d.nodeType&&
h.push(d);for(k=0;d=h[k++];)c=b,d=pa(d),d.length&&Y(d,c)}}}function qa(a){var b=a.indexOf("{{");return-1!==b&&b<a.indexOf("}}")}function ra(a){var b=[];if(qa(a)){do a=a.replace(Fa,function(a,c){c&&b.push({value:c,expr:!1});return""}),a=a.replace(Ga,function(a,c){if(c){var e=[];0<c.indexOf("|")&&(c=c.replace(/\|\s*(\w+)\s*(\([^)]+\))?/g,function(a,b,d){e.push(b+(d||""));return""}));b.push({value:c,expr:!0,filters:e.length?e:void 0})}return""});while(qa(a));a&&b.push({value:a,expr:!1})}return b}function Y(a,
b){a.forEach(function(a){q[a.type](a,b);a.remove&&a.element.removeAttribute(a.node.name)})}function pa(a){var b=[],d=ra(a.nodeValue);if(d.length){for(;d.length;){var c=d.shift(),e=w.createTextNode(c.value);if(c.expr){var f=c.filters,c={type:"text",node:e,args:[],element:a.parentNode,value:c.value,filters:f};f&&-1!==f.indexOf("html")&&(avalon.Array.remove(f,"html"),c.type="html",c.replace=!0);b.push(c)}H.appendChild(e)}a.parentNode.replaceChild(H,a)}return b}function sa(a,b){for(var d=a.split("."),
c=0,e,f;e=b[c++];)try{if(e.hasOwnProperty(d[0])&&(2>d.length||e[d[0]].hasOwnProperty(d[1]))){var g=Function("scope","value","if(arguments.length === 1){ return scope."+a+" }else{ scope."+a+" = value  }");g(e);f=e;break}}catch(h){}if(f)return[g,f]}function m(a,b,d,c,e){var f,g,h=d.filters;f=avalon.noop;!h&&!e&&(g=sa(a.trim(),b))&&(g=[g[0],[g[1]]]);!g&&!e&&(g=Z(a,b,d));if(!g&&e)g=e.map(function(a){return a.expr?Z(a.value,b,d)||"":a.value}),f=function(a,b){return function(){for(var c="",e,f=0,g;g=a[f++];)"string"===
typeof g?c+=g:(e=g[0],c+=e.apply(e,g[1]));return b(c,d.element)}}(g,c);else if(g){var k=g[0],l=g[1];f=function(){c(k.apply(k,l),d.element)}}f.toString=function(){return"eval("+a+")"};f.element=d.element;r[n]=f;V=!0;f();V=!1;delete r[n]}function Z(a,b,d){var c=[],e=[],f=new Date-0;b.forEach(function(a){var b=a.$id.replace(/-/g,"_")+""+f;-1===c.indexOf(b)&&(c.push(b),e.push(a))});a="var ret"+f+" = "+a+"\r\n";b=0;for(var g;g=c[b++];)a="with("+g+"){\r\n"+a+"}\r\n";if(d.filters){g=[];g.push(a,"\r\n");
b=0;for(var h;h=d.filters[b++];){var k=h.indexOf("(");-1!==k?(a=h.slice(k+1,h.lastIndexOf(")")).trim(),a=","+a,h=h.slice(0,k).trim()):a="";g.push(" if(filters",f,".",h,"){\r\n\ttry{ret",f," = filters",f,".",h,"(ret",f,a,")}catch(e){} \r\n}\r\n")}a=g.join("");c.push("filters"+f);e.push(avalon.filters);delete d.filters}try{var l=Function.apply(Function,c.concat(a+("\r\nreturn ret"+f)));l.apply(l,e);return[l,e]}catch(y){d.remove=!1}finally{g=c=null}}function Ha(a){var b=a.target=a.srcElement;a.which=
null!=a.charCode?a.charCode:a.keyCode;/mouse|click/.test(a.type)&&(b=b.ownerDocument||w,b="BackCompat"===b.compatMode?b.body:b.documentElement,a.pageX=a.clientX+(b.scrollLeft>>0)-(b.clientLeft>>0),a.pageY=a.clientY+(b.scrollTop>>0)-(b.clientTop>>0));a.preventDefault=function(){a.returnValue=!1};a.stopPropagation=function(){a.cancelBubble=!0};return a}function Ia(a,b){a=a.toLowerCase();if(!P[a]){var d=w.createElement(a);B.appendChild(d);b=window.getComputedStyle?window.getComputedStyle(d,null).display:
d.currentStyle.display;B.removeChild(d);P[a]=b}return P[a]}function ta(a,b){var d=s(a);/array|object/.test(d)&&(a=a.$id?a:G(a,a,"array"===d),this[b]=a.$model);return a}function ma(a,b,d){var c=a.map(ta,a);c.$id=L();c[A]=[];c.$model=c.$json=a;var e=G({length:a.length});e.$watch("length",function(){b&&b.$fire(d+".length")});"push,pop,shift,unshift,splice".replace(u,function(b){c[b]=function(){var c=this.length,d;if(/push|unshift|splice/.test(b)){d=[].slice.call(arguments);var k=d.map(ta,d);a[b].apply(a,
d);d=a[b].apply(this,k);z(this,b,k,c)}else a[b].call(this),d=a[b](),z(this,b,arguments,c);e.length=this.length;return d}});"sort,reverse".replace(u,function(b){c[b]=function(){a[b].apply(this,arguments);for(var d=this.map(function(a){return a&&a.$model?a.$model:a}),e=a.length,k=0;k<e;k++){var l=a[k];l!==d[k]&&(a.splice(k,1),a.push(l),z(c,"reroder",[k]),k-=1)}return this}});c.isCollection=!0;c.clear=function(){this.length=e.length=0;z(this,"clear",[]);return this};c.update=function(a){Array.isArray(a)&&
T(this,a,!0);return this};c.sortBy=function(b,d){this.update(avalon.Array.sortBy(a,b,d));return this};c.contains=function(a){return-1!==this.indexOf(a)};c.ensure=function(a){this.contains(a)||this.push(a);return this};c.set=function(a,c){0<=a&&a<this.length&&(/array|object/.test(s(c))?(b&&b.$fire(d+".changed"),c.$model&&(c=c.$model),T(this[a],c,Array.isArray(c))):this[a]!==c&&(this[a]=c,b&&b.$fire(d+".changed"),z(this,"set",arguments)));return this};c.size=function(){return e.length};c.remove=function(a){a=
this.indexOf(a);return this.removeAt(a)};c.removeAt=function(b){if(0<=b&&0===b%1)return a.splice(b,1),this.splice(b,1),this};c.removeAll=function(a){if(Array.isArray(a))a.forEach(function(a){c.remove(a)});else if("function"===typeof a)for(var b=this.length-1;0<=b;b--)a(this[b],b)&&this.splice(b,1);else this.clear()};return c}function Ja(a){for(;a.firstChild;)a.removeChild(a.firstChild)}function Ka(a,b,d){a=a.childNodes;return a[a.length/b.length*d]}function Q(a,b,d,c){var e=a.childNodes;a=b.length;
a=e.length/a;e=e[a*d];b=b[d].$view;d=[e];a*=c||1;for(c=1;c<a;c++)e=e.nextSibling,d.push(e);for(c=0;e=d[c++];)b.appendChild(e);return b}function I(a,b,d){b=b||0;d=d||0;for(var c;c=a[b++];)c.$index=d++}function ua(a,b,d,c,e){var f=c.scopes,g=c.element,h=La(a,b,d,c.args);b=[];c=c.view.cloneNode(!0);var k=c.childNodes,f=[h].concat(f);e.splice(a,0,h);h.$view=c;if(!g.inprocess){g.inprocess=1;var l=g.hidden;g.hidden=!0}for(a=0;e=k[a++];)1===e.nodeType?X(e,f):3===e.nodeType&&b.push(e);g.insertBefore(c,d.place||
null);for(a=0;e=b[a++];)d=f,e=pa(e),e.length&&Y(e,d);g.inprocess&&(g.hidden=l,g.inprocess=0)}function La(a,b,d,c){c=c[0]||"$data";var e={};e.$index=a;e.$view={};e.$itemName=c;e[c]={get:function(){return b},set:function(a){b=a}};e.$first={get:function(){return 0===this.$index}};e.$last={get:function(){return this.$index===d.length-1}};e.$remove=function(){return d.remove(b)};return G(e)}var r={},E=[],n=new Date-0,A="$"+n,N=!1,V=!1,u=/[^, ]+/g,ga={},$=Object.prototype,Ma=$.hasOwnProperty,t="ms-",va=
window.dispatchEvent,B=w.documentElement,ha=$.toString,J=document.createElement("div"),H=w.createDocumentFragment(),aa="propertyIsEnumerable isPrototypeOf hasOwnProperty toLocaleString toString valueOf constructor".split(" ");"Boolean Number String Function Array Date RegExp Object Error".replace(u,function(a){ga["[object "+a+"]"]=a.toLowerCase()});var Aa=/^[object (Window|DOMWindow|global)]$/;avalon=function(a){return new avalon.init(a)};avalon.init=function(a){this[0]=this.element=a};avalon.fn=
avalon.prototype=avalon.init.prototype;avalon.type=s;avalon.isWindow=function(a){return a&&a===a.window};ia(window)&&(avalon.isWindow=ia);avalon.isPlainObject=function(a){if("object"!==this.type(a)||a.nodeType||this.isWindow(a))return!1;try{if(a.constructor&&!Ma.call(a.constructor.prototype,"isPrototypeOf"))return!1}catch(b){return!1}return!0};/[native code]/.test(Object.getPrototypeOf)&&(avalon.isPlainObject=function(a){return a&&Object.getPrototypeOf({})===$});avalon.mix=avalon.fn.mix=function(){var a,
b,d,c,e,f=arguments[0]||{},g=1,h=arguments.length,k=!1;"boolean"===typeof f&&(k=f,f=arguments[1]||{},g=2);"object"!==typeof f&&"function"!==s(f)&&(f={});h===g&&(f=this,--g);for(;g<h;g++)if(null!=(a=arguments[g]))for(b in a)d=f[b],c=a[b],f!==c&&(k&&c&&(avalon.isPlainObject(c)||(e=Array.isArray(c)))?(e?(e=!1,d=d&&Array.isArray(d)?d:[]):d=d&&avalon.isPlainObject(d)?d:{},f[b]=avalon.mix(k,d,c)):void 0!==c&&(f[b]=c));return f};avalon.mix({rword:u,subscribers:A,ui:{},models:{},log:function(a){window.console&&
console.log(a)},noop:K,error:function(a,b){throw new (b||Error)(a);},ready:function(a){"function"===typeof a&&(Array.isArray(E)?E.push(a):a())},oneObject:function(a,b){"string"===typeof a&&(a=a.match(u)||[]);for(var d={},c=void 0!==b?b:1,e=0,f=a.length;e<f;e++)d[a[e]]=c;return d},range:function(a,b,d){d||(d=1);null==b&&(b=a||0,a=0);var c=-1;b=Math.max(0,Math.ceil((b-a)/d));for(var e=Array(b);++c<b;)e[c]=a,a+=d;return e},bind:function(a,b,d,c){function e(b){b=b.target?b:Ha(b||window.event);var c=d.call(a,
b);!1===c&&(b.preventDefault(),b.stopPropagation());return c}if(va)a.addEventListener(b,e,!!c);else try{a.attachEvent("on"+b,e)}catch(f){}return e},unbind:va?function(a,b,d,c){a.removeEventListener(b,d||K,!!c)}:function(a,b,d){a.detachEvent("on"+b,d||K)}});avalon.forEach=function(a,b){window.console&&console.log("\u6b64\u65b9\u6cd5\u5df2\u8fc7\u65f6,\u8bf7\u4f7f\u7528avalon.each");D(a,b)};avalon.each=D;avalon.bind(window,"load",ja);avalon.bind(window,"DOMContentLoaded",ja);var Ba=/^(?:null|false|true|NaN|\{.*\}|\[.*\])$/,
R=/\S+/g;avalon.fn.mix({hasClass:function(a){var b=this[0]||{};if(1===b.nodeType)return!!b.className&&-1<(" "+b.className+" ").indexOf(" "+a+" ")},addClass:function(a){var b=this[0];if(a&&"string"===typeof a&&b&&1===b.nodeType)if(b.className){a=(b.className+" "+a).match(R);a.sort();for(var d=a.length-1;0<d;--d)a[d]===a[d-1]&&a.splice(d,1);b.className=a.join(" ")}else b.className=a;return this},removeClass:function(a){var b=this[0];if(a&&"o"<typeof a&&b&&1===b.nodeType&&b.className){a=(a||"").match(R)||
[];for(var d=a.length,c=" "+b.className.match(R).join(" ")+" ",e=0;e<d;e++)c=c.replace(" "+a[e]+" "," ");b.className=c.slice(1,c.length-1)}return this},toggleClass:function(a,b){for(var d=b,c,e=0,f=a.match(R)||[],g="boolean"===typeof b;c=f[e++];)d=g?d:!this.hasClass(c),this[d?"addClass":"removeClass"](c);return this},attr:function(a,b){return 2===arguments.length?(this[0].setAttribute(a,b),this):this[0].getAttribute(a)},data:function(a,b){a="data-"+ka(a||"");switch(arguments.length){case 2:return this.attr(a,
b),this;case 1:var d=this.attr(a);return la(d);case 0:for(var d=this[0].attributes,c={},e=0,f;f=d[e++];)a=f.name,a.indexOf("data-")||(a=M(a.slice(5)),c[a]=la(f.value));return c}},removeData:function(a){a="data-"+ka(a);this[0].removeAttribute(a);return this},css:function(a,b){var d=this[0];if(d&&d.style){var c=/[_-]/.test(a)?M(a):a,e;a:{var f=e=void 0;if(ba[c])e=ba[c];else{e=e||B.style;for(var g=0,h=wa.length;g<h;g++)if(f=M(wa[g]+c),f in e){e=ba[c]=f;break a}e=null}}a=e||c;if(1===arguments.length)return c=
v[c+":get"]||v["@:get"],c(d,a);e=typeof b;if("number"!==e||isFinite(b+""))return"number"===e&&!Na[c]&&(b+="px"),c=v[c+":set"]||v["@:set"],c(d,a,b),this}},bind:function(a,b,d){if(this[0])return avalon.bind(this[0],a,b,d)},unbind:function(a,b,d){this[0]&&avalon.unbind(this[0],a,b,d);return this},val:function(a){var b=this[0];if(b&&1===b.nodeType){var d=0===arguments.length,c=d?":get":":set",e=ca,f;f=b.tagName.toLowerCase();f="input"===f&&/checkbox|radio/.test(b.type)?"checked":f;if(c=e[f+c])var g=c(b,
a);else{if(d)return(b.value||"").replace(/\r/g,"");b.value=a}}return d?g:this}});var v=avalon.cssHooks={},wa=["","-webkit-","-o-","-moz-","-ms-"],ba={"float":"cssFloat"in B.style?"cssFloat":"styleFloat",background:"backgroundColor"},Na=avalon.oneObject("columnCount,fillOpacity,fontWeight,lineHeight,opacity,orphans,widows,zIndex,zoom");v["@:set"]=function(a,b,d){a.style[b]=d};if(window.getComputedStyle)v["@:get"]=function(a,b){var d,c=window.getComputedStyle(a,null);c&&(d="filter"===b?c.getPropertyValue(b):
c[b],""===d&&(d=a.style[b]));return d};else{var Oa=/^-?(?:\d*\.)?\d+(?!px)[^\d\s]+$/i,Pa=/^(top|right|bottom|left)$/,da=!!window.XDomainRequest,Qa={thin:da?"1px":"2px",medium:da?"3px":"4px",thick:da?"5px":"6px"};v["@:get"]=function(a,b){var d=a.currentStyle,c=d[b];if(Oa.test(c)&&!Pa.test(c)){var e=a.style,f=e.left,g=a.runtimeStyle.left;a.runtimeStyle.left=d.left;e.left="fontSize"===b?"1em":c||0;c=e.pixelLeft+"px";e.left=f;a.runtimeStyle.left=g}"medium"===c&&(b=b.replace("Width","Style"),"none"===
d[b]&&(c="0px"));return""===c?"auto":Qa[c]||c};v["opacity:set"]=function(a,b){a.style.filter="alpha(opacity="+100*b+")";a.style.zoom=1};v["opacity:get"]=function(a){a=a.filters.alpha||a.filters["DXImageTransform.Microsoft.Alpha"];return(a?a.opacity:100)/100+""}}"Width,Height".replace(u,function(a){var b=a.toLowerCase(),d="client"+a,c="scroll"+a,e="offset"+a;avalon.fn[b]=function(f){var g=this[0];if(0===arguments.length){if(g.setTimeout)return g["inner"+a]||g.document.documentElement[d];if(9===g.nodeType){var h=
g.documentElement;return Math.max(g.body[c],h[c],g.body[e],h[e],h[d])}return parseFloat(this.css(b))||0}return this.css(b,f)}});avalon.fn.offset=function(){var a=this[0],b=a&&a.ownerDocument,d={left:0,top:0};if(!b)return d;var a=a.getBoundingClientRect(),c=b.defaultView||b.parentWindow,b=navigator.vendor||"BackCompat"===b.compatMode?b.body:b.documentElement,e=b.clientLeft>>0,f=c.pageXOffset||b.scrollLeft;d.top=a.top+(c.pageYOffset||b.scrollTop)-(b.clientTop>>0);d.left=a.left+f-e;return d};var ca=
{"option:get":function(a){var b=a.attributes.value;return!b||b.specified?a.value:a.text},"select:get":function(a,b){for(var d,c=a.options,e=a.selectedIndex,f=ca["option:get"],g="select-one"===a.type||0>e,h=g?null:[],k=g?e+1:c.length,l=0>e?k:g?e:0;l<k;l++)if(d=c[l],(d.selected||l===e)&&!d.disabled){b=f(d);if(g)return b;h.push(b)}return h},"select:set":function(a,b){b=[].concat(b);for(var d=ca["option:get"],c=0,e;e=a.options[c++];)e.selected=!!~b.indexOf(d(e));b.length||(a.selectedIndex=-1)}};"\u53f8\u5f92\u6b63\u7f8e".trim||
(String.prototype.trim=function(){return this.replace(/^[\s\xA0]+/,"").replace(/[\s\xA0]+$/,"")});for(var Ta in{toString:1})aa=!1;Object.keys||(Object.keys=function(a){var b=[],d;for(d in a)a.hasOwnProperty(d)&&b.push(d);if(aa&&a)for(var c=0;d=aa[c++];)a.hasOwnProperty(d)&&b.push(d);return b});Array.isArray||(Array.isArray=function(a){return"array"===s(a)});Function.prototype.bind||(Function.prototype.bind=function(a){if(2>arguments.length&&void 0===a)return this;var b=this,d=arguments;return function(){var c=
[],e;for(e=1;e<d.length;e++)c.push(d[e]);for(e=0;e<arguments.length;e++)c.push(arguments[e]);return b.apply(a,c)}});avalon.mix(Array.prototype,{indexOf:function(a,b){var d=this.length,c=~~b;for(0>c&&(c+=d);c<d;c++)if(this[c]===a)return c;return-1},lastIndexOf:function(a,b){var d=this.length,c=null==b?d-1:b;for(0>c&&(c=Math.max(0,d+c));0<=c;c--)if(this[c]===a)return c;return-1},forEach:F("","_",""),filter:F("r=[],j=0,","if(_)r[j++]=this[i]","return r"),map:F("r=[],","r[i]=_","return r"),some:F("",
"if(_)return true","return false"),every:F("","if(!_)return false","return true")});avalon.Array={sortBy:function(a,b,d){a=a.map(function(a,e){return{el:a,re:b.call(d,a,e)}}).sort(function(a,b){var d=a.re,g=b.re;return d<g?-1:d>g?1:0});return avalon.Array.pluck(a,"el")},pluck:function(a,b){return a.filter(function(a){return null!=a[b]})},ensure:function(a){[].slice.call(arguments,1).forEach(function(b){~a.indexOf(b)||a.push(b)});return a},removeAt:function(a,b){return!!a.splice(b,1).length},remove:function(a,
b){var d=a.indexOf(b);return~d?avalon.Array.removeAt(a,d):!1}};var S;"function"===typeof setImmediate?S=setImmediate.bind(window):function(){function a(){--e;if(++g>=c){g=0;c*=4;for(var a=f&&Math.min(f-1,c);e<a;)++e,h()}for(;f;)--f,b=b.next,a=b.task,b.task=void 0,a();g=0}var b={task:void 0,next:null},d=b,c=2,e=0,f=0,g=0,h=void 0;S=function(a){d=d.next={task:a,next:null};e<++f&&e<c&&(++e,h())};if("undefined"!==typeof MessageChannel){var k=new MessageChannel;k.port1.onmessage=a;h=function(){k.port2.postMessage(0)}}else h=
function(){setTimeout(a,0)}}();avalon.nextTick=S;avalon.define=function(a,b,d){var c=[].slice.call(arguments);"string"!==typeof a&&(a=L(),c.unshift(a));Array.isArray(c[1])||c.splice(1,0,[]);b=c[1];"function"!==typeof c[2]&&avalon.error("factory\u5fc5\u987b\u662f\u51fd\u6570");d=c[2];c={$watch:K};b.unshift(c);d(c);c=G(c);N=!0;b[0]=c;d.apply(0,b);b.shift();N=!1;c.$id=a;return avalon.models[a]=c};var W={$watch:function(a,b){var d=this.$events[a];d?d.push(b):this.$events[a]=[b];return this},$unwatch:function(a,
b){var d=arguments.length;if(0===d)this.$events={};else if(1===d)this.$events[a]=[];else for(var d=this.$events[a]||[],c=d.length;-1<--c;)if(d[c]===b)return d.splice(c,1);return this},$fire:function(a){for(var b=this.$events[a]||[],d=this.$events.$all||[],c=[].slice.call(arguments,1),e=0,f;f=b[e++];)f.apply(this,c);for(e=0;f=d[e++];)f.apply(this,c)}},Ca=avalon.oneObject("$index,$remove,$first,$last"),U=avalon.oneObject("$id,$skipArray,$watch,$unwatch,$fire,$events,$json,$model"),ea=Object.defineProperty;
try{ea({},"_",{value:"x"});var O=Object.defineProperties}catch(Ua){"__defineGetter__"in avalon&&(ea=function(a,b,d){"value"in d&&(a[b]=d.value);"get"in d&&a.__defineGetter__(b,d.get);"set"in d&&a.__defineSetter__(b,d.set);return a},O=function(a,b){for(var d in b)b.hasOwnProperty(d)&&ea(a,d,b[d]);return a})}if(!O&&window.VBArray){window.execScript("Function parseVB(code)\n\tExecuteGlobal(code)\nEnd Function","VBScript");var Ra=function(a,b,d){var c=a[b]&&a[b].set;if(3===arguments.length)c(d);else return c()},
O=function(a,b,d){a=d.slice(0);a.push("hasOwnProperty");d="VBClass"+setTimeout("1");var c={},e=[];e.push("Class "+d,"\tPrivate [__data__], [__proxy__]","\tPublic Default Function [__const__](d, p)","\t\tSet [__data__] = d: set [__proxy__] = p","\t\tSet [__const__] = Me","\tEnd Function");a.forEach(function(a){!0!==c[a]&&(c[a]=!0,e.push("\tPublic ["+a+"]"))});Object.keys(b).forEach(function(a){c[a]=!0;e.push("\tPublic Property Let ["+a+"](val)",'\t\tCall [__proxy__]([__data__], "'+a+'", val)',"\tEnd Property",
"\tPublic Property Set ["+a+"](val)",'\t\tCall [__proxy__]([__data__], "'+a+'", val)',"\tEnd Property","\tPublic Property Get ["+a+"]","\tOn Error Resume Next","\t\tSet["+a+'] = [__proxy__]([__data__],"'+a+'")',"\tIf Err.Number <> 0 Then","\t\t["+a+'] = [__proxy__]([__data__],"'+a+'")',"\tEnd If","\tOn Error Goto 0","\tEnd Property")});e.push("End Class");e.push("Function "+d+"Factory(a, b)","\tDim o","\tSet o = (New "+d+")(a, b)","\tSet "+d+"Factory = o","End Function");window.parseVB(e.join("\r\n"));
return window[d+"Factory"](b,Ra)}}avalon.scan=function(a,b){a=a||B;var d=b?[].concat(b):[];X(a,d)};var Ea=/\{\{[^}]*\}\}|\sms-/,Da=avalon.oneObject("area,base,basefont,br,col,hr,img,input,link,meta,param,embed,wbr,script,style,textarea"),Fa=/([^{]*)\{\{/,Ga=/([^}]*)\}\}/,P=avalon.oneObject("a,abbr,b,span,strong,em,font,i,kbd","inline");avalon.mix(P,avalon.oneObject("div,h1,h2,h3,h4,h5,h6,section,p","block"));J.setAttribute("className","t");var Sa="t"===J.className,xa={"class":"className","for":"htmlFor"},
q=avalon.bindingHandlers={"if":function(a,b){var d=w.createComment("@"),c=a.element.parentNode;m(a.value,b,a,function(a,b){if(a){if(!b.parentNode||11===b.parentNode.nodeType)c.replaceChild(b,d),b.noRemove=0}else b.parentNode&&1===b.parentNode.nodeType&&(c.replaceChild(d,b),b.noRemove=1)})},template:function(a,b){m(a.value,b,a,function(b,c){var e=a.args.join("-"),f=w.getElementById(e);f&&b.$model&&S(function(){c.innerHTML=f.text;avalon.scan(c,b)})})},attr:function(a,b){a.remove=!1;m(a.value,b,a,function(b,
c){var e=a.node.name,f=!1===b||null===b||void 0===b;f&&c.removeAttribute(e);Sa&&e in xa?(e=xa[e],f?c.removeAttribute(e):c[e]=b):f||c.setAttribute(e,b)})},on:function(a,b){m(a.value,b,a,function(d,c){var e=a.args[0];e&&"function"===typeof d&&(c.$vmodels||(c.$vmodel=c.$scope=b[0],c.$vmodels=b),avalon.bind(c,e,d))})},data:function(a,b){m(a.value,b,a,function(b,c){var e="data-"+a.args.join("-");c.setAttribute(e,b)})},text:function(a,b){m(a.value,b,a,function(b){a.node.nodeValue=b})},visible:function(a,
b){var d=a.element,c=avalon(d).css("display"),c="none"===c?Ia(d.tagName):c;m(a.value,b,a,function(a){d.style.display=a?c:"none"})},href:function(a,b){var d=a.value.trim(),c=!0,e=a.type;-1<d.indexOf("{{")&&2<d.indexOf("}}")&&(c=!1,/^\{\{([^}]+)\}\}$/.test(d)&&(c=!0,d=RegExp.$1));m(d,b,a,function(b,c){"css"===e?avalon(c).css(a.args.join("-"),b):c[e]=b},c?null:ra(a.value))},disabled:function(a,b){var d=a.type,c="readonly"===d?"readOnly":d;m(a.value,b,a,function(a,b){b[c]=!!a})},bind:function(a,b){for(var d=
a.value.trim(),c=a.args[0],e=0,f;f=b[e++];)if(f.hasOwnProperty(d)){d=f[d];break}"function"===typeof d&&f.$watch(c,function(b,c){d.call(a.element,b,c)})},"class":function(a,b){m(a.value,b,a,function(d,c){var e=a.args.join("-");"function"===typeof d&&(c.$vmodels||(c.$vmodel=c.$scope=b[0],c.$vmodels=b),d=d.call(c));avalon(c).toggleClass(e,!!d)})},hover:function(a){var b=avalon(a.element);b.bind("mouseenter",function(){b.addClass(a.value)});b.bind("mouseleave",function(){b.removeClass(a.value)})},active:function(a){var b=
a.element,d=avalon(b);b.tabIndex=b.tabIndex||-1;d.bind("focus",function(){d.addClass(a.value)});d.bind("blur",function(){d.removeClass(a.value)})},html:function(a,b){m(a.value,b,a,function(b,c){b=null==b?"":b+"";if(a.replace){for(J.innerHTML=b;J.firstChild;)H.appendChild(J.firstChild);c.replaceChild(H,a.node)}else c.innerHTML=b})},ui:function(a,b,d){var c=a.value.trim();if("function"===typeof avalon.ui[c]){var e=(avalon(a.element).data("id")||"").trim(),e=e||c+setTimeout("1");a.element.setAttribute(t+
"controller",e);var f=a.args[0];if(f){for(var g=0,h;h=b[g++];)if(h.hasOwnProperty(f)){d=h[f];break}if(!d)for(g in avalon.models)if(h=avalon.models[g],h.hasOwnProperty(f)){d=h[f];break}}avalon.ui[c](a.element,e,d)}}};"checked,readonly,selected".replace(u,function(a){q[a]=q.disabled});q.enabled=function(a,b){m(a.value,b,a,function(a,b){b.disabled=!a})};"title,alt,src,value,css".replace(u,function(a){q[a]=q.href});var C=q.model=function(a,b){var d=a.element,c=d.tagName;if("function"===typeof C[c]){var e=
sa(a.value.trim(),b);if(e)C[c](d,e[0],e[1])}};C.INPUT=function(a,b,d){void 0===a.name&&(a.name=L());var c=a.type,e=avalon(a),f=function(){!1!==e.data("observe")&&b(d,a.value)},g=function(){var c=b(d);c!==a.value&&(a.value=c)};/^(password|textarea|text)$/.test(c)?(c=a.attributes[t+"event"]||{},c=c.value,"change"===c?avalon.bind(a,c,f):(window.addEventListener?a.addEventListener("input",f,!1):a.attachEvent("onpropertychange",f),9<=w.documentMode&&(a.attachEvent("onkeydown",function(a){a=a.keyCode;(8===
a||46===a)&&f()}),a.attachEvent("oncut",f)))):"radio"===c?(g=function(){a.checked=!!b(d)},f=function(){if(!1!==e.data("observe")){var c=!a.beforeChecked;b(d,c);a.beforeChecked=a.checked=c}},c=function(){a.beforeChecked=a.checked},null===a.onbeforeactivate?e.bind("beforeactivate",c):e.bind("mouseover",c),e.bind("click",f)):"checkbox"===c&&(f=function(){if(!1!==e.data("observe"))avalon.Array[a.checked?"ensure":"remove"](b(d),a.value)},g=function(){var c=[].concat(b(d));a.checked=0<=c.indexOf(a.value)},
e.bind("click",f));r[n]=g;g.element=a;g();delete r[n]};C.SELECT=function(a,b,d,c){function e(){var a=b(d);a+""!==c&&(f.val(a),c=a+"")}var f=avalon(a);f.bind("change",function(){if(!1!==f.data("observe")){var a=f.val();a+""!==c&&(b(d,a),c=a+"")}});r[n]=e;e.element=a;e();delete r[n]};C.TEXTAREA=C.INPUT;"dblclick,mouseout,click,mouseover,mouseenter,mouseleave,mousemove,mousedown,mouseup,keypress,keydown,keyup,blur,focus,change".replace(u,function(a){q[a]=function(b){b.args=[a];q.on.apply(0,arguments)}});
if(!("onmouseenter"in B)){var ya=avalon.bind,za={mouseenter:"mouseover",mouseleave:"mouseout"};avalon.bind=function(a,b,d){return za[b]?ya(a,za[b],function(c){var e=c.relatedTarget;if(!e||e!==a&&!(a.compareDocumentPosition(e)&16))return delete c.type,c.type=b,d.call(a,c)}):ya(a,b,d)}}q.each=function(a,b){function d(b,e,k){var l=d.vmodels;switch(b){case "reroder":b=e[0];e=l.splice(b,1);l.push(e[0]);b=Q(c,l,b);c.appendChild(b);I(l);break;case "set":(b=l[e[0]])&&(b[b.$itemName]=e[1]);break;case "push":D(e,
function(b,c){ua(k+b,c,f,a,l)});break;case "unshift":I(l,0,f.length-k);f.place=c.firstChild;D(e,function(b,c){ua(b,c,f,a,l)});f.place=null;break;case "pop":var y=Q(c,l,l.length-1);y&&l.pop();break;case "shift":if(y=Q(c,l,0))l.shift(),I(l);break;case "splice":b=e[0];y=e[1];e=[].slice.call(e,2);var x=0<=y?y:k-b;if(x&&(y=Q(c,l,b,x)))l.splice(b,x),I(l,b,b);e.length&&(f.place=Ka(c,l,b),d("push",e,b),I(l,b,b),f.place=null);break;case "clear":l.length=0,Ja(c)}}var c=a.element,e=Z(a.value,b,a),f;"object"==
typeof e&&(f=e[0].apply(e[0],e[1]));if("object"!==typeof f)return f;for(e=H.cloneNode(!1);c.firstChild;)e.appendChild(c.firstChild);a.view=e;a.scopes=b;d.vmodels=[];(f||{}).isCollection&&f[A].push(d);d("push",f,0)};var fa=avalon.filters={uppercase:function(a){return a.toUpperCase()},html:function(a){return a},lowercase:function(a){return a.toLowerCase()},truncate:function(a,b,d){b=b||30;d=void 0===d?"...":d;return a.length>b?a.slice(0,b-d.length)+d:String(a)},camelize:M,escape:function(a){return a.replace(/&/g,
"&amp ").replace(/</g,"&lt ").replace(/>/g,"&gt ").replace(/"/g,"&quot ").replace(/'/g,"&#39 ")},currency:function(a,b){return(b||"\uffe5")+avalon.filters.number(a)},number:function(a,b,d,c){a=(a+"").replace(/[^0-9+\-Ee.]/g,"");a=!isFinite(+a)?0:+a;b=!isFinite(+b)?0:Math.abs(b);c=c||",";d=d||".";var e="",e=function(a,b){var c=Math.pow(10,b);return""+Math.round(a*c)/c},e=(b?e(a,b):""+Math.round(a)).split(".");3<e[0].length&&(e[0]=e[0].replace(/\B(?=(?:\d{3})+(?!\d))/g,c));if((e[1]||"").length<b)e[1]=
e[1]||"",e[1]+=Array(b-e[1].length+1).join("0");return e.join(d)}};new function(){function a(a,b,c){var d="";0>a&&(d="-",a=-a);for(a=""+a;a.length<b;)a="0"+a;c&&(a=a.substr(a.length-b));return d+a}function b(b,c,d,e){return function(f){f=f["get"+b]();if(0<d||f>-d)f+=d;0===f&&-12===d&&(f=12);return a(f,c,e)}}function d(a,b){return function(c,d){var e=c["get"+a](),f=(b?"SHORT"+a:a).toUpperCase();return d[f][e]}}function c(a){var b;if(b=a.match(h)){a=new Date(0);var c=0,d=0,e=b[8]?a.setUTCFullYear:a.setFullYear,
f=b[8]?a.setUTCHours:a.setHours;b[9]&&(c=parseInt(b[9]+b[10],10),d=parseInt(b[9]+b[11],10));e.call(a,parseInt(b[1],10),parseInt(b[2],10)-1,parseInt(b[3],10));f.call(a,parseInt(b[4]||0,10)-c,parseInt(b[5]||0,10)-d,parseInt(b[6]||0,10),parseInt(b[7]||0,10))}return a}var e={yyyy:b("FullYear",4),yy:b("FullYear",2,0,!0),y:b("FullYear",1),MMMM:d("Month"),MMM:d("Month",!0),MM:b("Month",2,1),M:b("Month",1,1),dd:b("Date",2),d:b("Date",1),HH:b("Hours",2),H:b("Hours",1),hh:b("Hours",2,-12),h:b("Hours",1,-12),
mm:b("Minutes",2),m:b("Minutes",1),ss:b("Seconds",2),s:b("Seconds",1),sss:b("Milliseconds",3),EEEE:d("Day"),EEE:d("Day",!0),a:function(a,b){return 12>a.getHours()?b.AMPMS[0]:b.AMPMS[1]},Z:function(b){b=-1*b.getTimezoneOffset();return b=(0<=b?"+":"")+(a(Math[0<b?"floor":"ceil"](b/60),2)+a(Math.abs(b%60),2))}},f=/((?:[^yMdHhmsaZE']+)|(?:'(?:[^']|'')*')|(?:E+|y+|M+|d+|H+|h+|m+|s+|a|Z))(.*)/,g=/^\d+$/,h=/^(\d{4})-?(\d\d)-?(\d\d)(?:T(\d\d)(?::?(\d\d)(?::?(\d\d)(?:\.(\d+))?)?)?(Z|([+-])(\d\d):?(\d\d))?)?$/;
fa.date=function(a,b){var d=fa.date.locate,h="",k=[],m,n;b=b||"mediumDate";b=d[b]||b;"string"===typeof a&&(a=g.test(a)?parseInt(a,10):c(a));"number"===s(a)&&(a=new Date(a));if("date"===s(a)){for(;b;)(n=f.exec(b))?(k=k.concat(n.slice(1)),b=k.pop()):(k.push(b),b=null);k.forEach(function(b){m=e[b];h+=m?m(a,d):b.replace(/(^'|'$)/g,"").replace(/''/g,"'")});return h}};var k={AMPMS:{"0":"\u4e0a\u5348",1:"\u4e0b\u5348"},DAY:{"0":"\u661f\u671f\u65e5",1:"\u661f\u671f\u4e00",2:"\u661f\u671f\u4e8c",3:"\u661f\u671f\u4e09",
4:"\u661f\u671f\u56db",5:"\u661f\u671f\u4e94",6:"\u661f\u671f\u516d"},MONTH:{"0":"1\u6708",1:"2\u6708",2:"3\u6708",3:"4\u6708",4:"5\u6708",5:"6\u6708",6:"7\u6708",7:"8\u6708",8:"9\u6708",9:"10\u6708",10:"11\u6708",11:"12\u6708"},SHORTDAY:{"0":"\u5468\u65e5",1:"\u5468\u4e00",2:"\u5468\u4e8c",3:"\u5468\u4e09",4:"\u5468\u56db",5:"\u5468\u4e94",6:"\u5468\u516d"},fullDate:"y\u5e74M\u6708d\u65e5EEEE",longDate:"y\u5e74M\u6708d\u65e5",medium:"yyyy-M-d ah:mm:ss",mediumDate:"yyyy-M-d",mediumTime:"ah:mm:ss",
"short":"yy-M-d ah:mm",shortDate:"yy-M-d",shortTime:"ah:mm"};k.SHORTMONTH=k.MONTH;fa.date.locate=k};avalon.ready(function(){avalon.scan(document.body)})})(document);
