define(function() {
    return [{
            "name": "Average.queue.Length",
            "resource_id": "f90af1c6-3dad-3f9c-9d0f-8a8d89420f4f",
            "resource_name": "PhysicalNode:master",
            "selected": false,
            "service": "Hardware/IO"
        }, {
            "name": "Average.queue.Length",
            "resource_id": "f9b44b21-8321-38a1-a1ae-860b8ff04c1f",
            "resource_name": "Disk:master-sda",
            "selected": false,
            "service": "Hardware/IO"
        }, {
            "name": "Buffer.Memory",
            "resource_id": "f90af1c6-3dad-3f9c-9d0f-8a8d89420f4f",
            "resource_name": "PhysicalNode:master",
            "selected": true,
            "service": "Hardware/Memory"
        }, {
            "name": "CPU.Guest",
            "resource_id": "f90af1c6-3dad-3f9c-9d0f-8a8d89420f4f",
            "resource_name": "PhysicalNode:master",
            "selected": false,
            "service": "Hardware/CPU"
        }, {
            "name": "CPU.HardIRQ",
            "resource_id": "f90af1c6-3dad-3f9c-9d0f-8a8d89420f4f",
            "resource_name": "PhysicalNode:master",
            "selected": false,
            "service": "Hardware/CPU"
        }, {
            "name": "CPU.IOWait",
            "resource_id": "f90af1c6-3dad-3f9c-9d0f-8a8d89420f4f",
            "resource_name": "PhysicalNode:master",
            "selected": false,
            "service": "Hardware/CPU"
        }, {
            "name": "CPU.Nice",
            "resource_id": "f90af1c6-3dad-3f9c-9d0f-8a8d89420f4f",
            "resource_name": "PhysicalNode:master",
            "selected": false,
            "service": "Hardware/CPU"
        }, {
            "name": "CPU.SoftIRQ",
            "resource_id": "f90af1c6-3dad-3f9c-9d0f-8a8d89420f4f",
            "resource_name": "PhysicalNode:master",
            "selected": false,
            "service": "Hardware/CPU"
        }, {
            "name": "CPU.Steal",
            "resource_id": "f90af1c6-3dad-3f9c-9d0f-8a8d89420f4f",
            "resource_name": "PhysicalNode:master",
            "selected": false,
            "service": "Hardware/CPU"
        }, {
            "name": "CPU.Sys",
            "resource_id": "f90af1c6-3dad-3f9c-9d0f-8a8d89420f4f",
            "resource_name": "PhysicalNode:master",
            "selected": true,
            "service": "Hardware/CPU"
        }, {
            "name": "CPU.User",
            "resource_id": "f90af1c6-3dad-3f9c-9d0f-8a8d89420f4f",
            "resource_name": "PhysicalNode:master",
            "selected": false,
            "service": "Hardware/CPU"
        }, {
            "name": "CPU.Util",
            "resource_id": "f90af1c6-3dad-3f9c-9d0f-8a8d89420f4f",
            "resource_name": "PhysicalNode:master",
            "selected": false,
            "service": "Hardware/CPU"
        }, {
            "name": "Cached.Memory",
            "resource_id": "f90af1c6-3dad-3f9c-9d0f-8a8d89420f4f",
            "resource_name": "PhysicalNode:master",
            "selected": false,
            "service": "Hardware/Memory"
        }, {
            "name": "Capacity.Total",
            "resource_id": "d531a730-5186-3e10-88c1-38befdef3fe1",
            "resource_name": "Ceph OSD ID:0",
            "selected": false,
            "service": "Service/Ceph"
        }, {
            "name": "Capacity.Used",
            "resource_id": "d531a730-5186-3e10-88c1-38befdef3fe1",
            "resource_name": "Ceph OSD ID:0",
            "selected": false,
            "service": "Service/Ceph"
        }, {
            "name": "Context.Switches",
            "resource_id": "f90af1c6-3dad-3f9c-9d0f-8a8d89420f4f",
            "resource_name": "PhysicalNode:master",
            "selected": false,
            "service": "Hardware/CPU"
        }, {
            "name": "Degraded",
            "resource_id": "5d26cacf-3c61-324a-a9c2-2b6d57d6e1c5",
            "resource_name": "Ceph Cluster Id:27d39faa-48ae-4356-a8e3-19d5b81e179e",
            "selected": false,
            "service": "Service/Ceph"
        }, {
            "name": "Existing.threads",
            "resource_id": "f90af1c6-3dad-3f9c-9d0f-8a8d89420f4f",
            "resource_name": "PhysicalNode:master",
            "selected": false,
            "service": "Hardware/Load"
        }, {
            "name": "Free.Memory",
            "resource_id": "f90af1c6-3dad-3f9c-9d0f-8a8d89420f4f",
            "resource_name": "PhysicalNode:master",
            "selected": false,
            "service": "Hardware/Memory"
        }, {
            "name": "Healthy",
            "resource_id": "5d26cacf-3c61-324a-a9c2-2b6d57d6e1c5",
            "resource_name": "Ceph Cluster Id:27d39faa-48ae-4356-a8e3-19d5b81e179e",
            "selected": true,
            "service": "Service/Ceph"
        }, {
            "name": "Load.averaged.over.1.minute",
            "resource_id": "f90af1c6-3dad-3f9c-9d0f-8a8d89420f4f",
            "resource_name": "PhysicalNode:master",
            "selected": false,
            "service": "Hardware/Load"
        }, {
            "name": "Load.averaged.over.15.minute",
            "resource_id": "f90af1c6-3dad-3f9c-9d0f-8a8d89420f4f",
            "resource_name": "PhysicalNode:master",
            "selected": true,
            "service": "Hardware/Load"
        }, {
            "name": "Load.averaged.over.5.minute",
            "resource_id": "f90af1c6-3dad-3f9c-9d0f-8a8d89420f4f",
            "resource_name": "PhysicalNode:master",
            "selected": false,
            "service": "Hardware/Load"
        }, {
            "name": "Network.Byte.in",
            "resource_id": "f90af1c6-3dad-3f9c-9d0f-8a8d89420f4f",
            "resource_name": "PhysicalNode:master",
            "selected": true,
            "service": "Hardware/Network"
        }, {
            "name": "Network.Byte.out",
            "resource_id": "f90af1c6-3dad-3f9c-9d0f-8a8d89420f4f",
            "resource_name": "PhysicalNode:master",
            "selected": false,
            "service": "Hardware/Network"
        }, {
            "name": "Network.Package.in",
            "resource_id": "f90af1c6-3dad-3f9c-9d0f-8a8d89420f4f",
            "resource_name": "PhysicalNode:master",
            "selected": false,
            "service": "Hardware/Network"
        }, {
            "name": "Network.Package.out",
            "resource_id": "f90af1c6-3dad-3f9c-9d0f-8a8d89420f4f",
            "resource_name": "PhysicalNode:master",
            "selected": false,
            "service": "Hardware/Network"
        }, {
            "name": "Percentage.time.of.IO.operations",
            "resource_id": "f90af1c6-3dad-3f9c-9d0f-8a8d89420f4f",
            "resource_name": "PhysicalNode:master",
            "selected": false,
            "service": "Hardware/IO"
        }, {
            "name": "Percentage.time.of.IO.operations",
            "resource_id": "f9b44b21-8321-38a1-a1ae-860b8ff04c1f",
            "resource_name": "Disk:master-sda",
            "selected": false,
            "service": "Hardware/IO"
        }, {
            "name": "Process.Creation",
            "resource_id": "f90af1c6-3dad-3f9c-9d0f-8a8d89420f4f",
            "resource_name": "PhysicalNode:master",
            "selected": false,
            "service": "Hardware/CPU"
        }, {
            "name": "Read.Bandwidth",
            "resource_id": "5d26cacf-3c61-324a-a9c2-2b6d57d6e1c5",
            "resource_name": "Ceph Cluster Id:27d39faa-48ae-4356-a8e3-19d5b81e179e",
            "selected": false,
            "service": "Service/Ceph"
        }, {
            "name": "Read.IO.Operations",
            "resource_id": "f90af1c6-3dad-3f9c-9d0f-8a8d89420f4f",
            "resource_name": "PhysicalNode:master",
            "selected": false,
            "service": "Hardware/IO"
        }, {
            "name": "Read.IO.Operations",
            "resource_id": "f9b44b21-8321-38a1-a1ae-860b8ff04c1f",
            "resource_name": "Disk:master-sda",
            "selected": false,
            "service": "Hardware/IO"
        }, {
            "name": "Read.Merged.Operations",
            "resource_id": "f90af1c6-3dad-3f9c-9d0f-8a8d89420f4f",
            "resource_name": "PhysicalNode:master",
            "selected": false,
            "service": "Hardware/IO"
        }, {
            "name": "Read.Merged.Operations",
            "resource_id": "f9b44b21-8321-38a1-a1ae-860b8ff04c1f",
            "resource_name": "Disk:master-sda",
            "selected": false,
            "service": "Hardware/IO"
        }, {
            "name": "Read.Operation",
            "resource_id": "5d26cacf-3c61-324a-a9c2-2b6d57d6e1c5",
            "resource_name": "Ceph Cluster Id:27d39faa-48ae-4356-a8e3-19d5b81e179e",
            "selected": false,
            "service": "Service/Ceph"
        }, {
            "name": "Read.Sectors.Number",
            "resource_id": "f90af1c6-3dad-3f9c-9d0f-8a8d89420f4f",
            "resource_name": "PhysicalNode:master",
            "selected": false,
            "service": "Hardware/IO"
        }, {
            "name": "Read.Sectors.Number",
            "resource_id": "f9b44b21-8321-38a1-a1ae-860b8ff04c1f",
            "resource_name": "Disk:master-sda",
            "selected": false,
            "service": "Hardware/IO"
        }, {
            "name": "Running.processes",
            "resource_id": "f90af1c6-3dad-3f9c-9d0f-8a8d89420f4f",
            "resource_name": "PhysicalNode:master",
            "selected": false,
            "service": "Hardware/Load"
        }, {
            "name": "Size.per.IO.Operation",
            "resource_id": "f90af1c6-3dad-3f9c-9d0f-8a8d89420f4f",
            "resource_name": "PhysicalNode:master",
            "selected": false,
            "service": "Hardware/IO"
        }, {
            "name": "Size.per.IO.Operation",
            "resource_id": "f9b44b21-8321-38a1-a1ae-860b8ff04c1f",
            "resource_name": "Disk:master-sda",
            "selected": false,
            "service": "Hardware/IO"
        }, {
            "name": "Swap.in.Page",
            "resource_id": "f90af1c6-3dad-3f9c-9d0f-8a8d89420f4f",
            "resource_name": "PhysicalNode:master",
            "selected": false,
            "service": "Hardware/Memory"
        }, {
            "name": "Swap.out.Page",
            "resource_id": "f90af1c6-3dad-3f9c-9d0f-8a8d89420f4f",
            "resource_name": "PhysicalNode:master",
            "selected": false,
            "service": "Hardware/Memory"
        }, {
            "name": "Ticks.of.per.request.in.queue",
            "resource_id": "f90af1c6-3dad-3f9c-9d0f-8a8d89420f4f",
            "resource_name": "PhysicalNode:master",
            "selected": false,
            "service": "Hardware/IO"
        }, {
            "name": "Ticks.of.per.request.in.queue",
            "resource_id": "f9b44b21-8321-38a1-a1ae-860b8ff04c1f",
            "resource_name": "Disk:master-sda",
            "selected": false,
            "service": "Hardware/IO"
        }, {
            "name": "Ticks.per.IO.operation.in.queue.Time",
            "resource_id": "f90af1c6-3dad-3f9c-9d0f-8a8d89420f4f",
            "resource_name": "PhysicalNode:master",
            "selected": false,
            "service": "Hardware/IO"
        }, {
            "name": "Ticks.per.IO.operation.in.queue.Time",
            "resource_id": "f9b44b21-8321-38a1-a1ae-860b8ff04c1f",
            "resource_name": "Disk:master-sda",
            "selected": false,
            "service": "Hardware/IO"
        }, {
            "name": "Total.Memory",
            "resource_id": "f90af1c6-3dad-3f9c-9d0f-8a8d89420f4f",
            "resource_name": "PhysicalNode:master",
            "selected": false,
            "service": "Hardware/Memory"
        }, {
            "name": "Unavailability",
            "resource_id": "5d26cacf-3c61-324a-a9c2-2b6d57d6e1c5",
            "resource_name": "Ceph Cluster Id:27d39faa-48ae-4356-a8e3-19d5b81e179e",
            "selected": false,
            "service": "Service/Ceph"
        }, {
            "name": "Used.Memory",
            "resource_id": "f90af1c6-3dad-3f8c-9d0f-8a8d89420f4f",
            "resource_name": "PhysicalNode:master",
            "selected": false,
            "service": "Hardware/Memory"
        }, {
            "name": "Utilization",
            "resource_id": "f90af1c6-3d2d-3f9c-9d0f-8a8d89420f4f",
            "resource_name": "PhysicalNode:master",
            "selected": false,
            "service": "Hardware/Memory"
        }, {
            "name": "Write.Bandwidth",
            "resource_id": "5d26cacf-3c61-324a-a9c2-2b6d57d6e1c5",
            "resource_name": "Ceph Cluster Id:27d39faa-48ae-4356-a8e3-19d5b81e179e",
            "selected": false,
            "service": "Service/Ceph"
        }, {
            "name": "Write.IO.Operations",
            "resource_id": "f90af1c6-3dad-3f9c-9d0f-8a8d89420f4f",
            "resource_name": "PhysicalNode:master",
            "selected": false,
            "service": "Hardware/IO"
        }, {
            "name": "Write.IO.Operations",
            "resource_id": "f9b44b21-8321-38a1-a1ae-860b8ff04c1f",
            "resource_name": "Disk:master-sda",
            "selected": false,
            "service": "Hardware/IO"
        }, {
            "name": "Write.Merged.Operations",
            "resource_id": "f90af1c6-3dad-3f9c-9d0f-8a8d89420f4f",
            "resource_name": "PhysicalNode:master",
            "selected": false,
            "service": "Hardware/IO"
        }, {
            "name": "Write.Merged.Operations",
            "resource_id": "f9b44b21-8321-38a1-a1ae-860b8ff04c1f",
            "resource_name": "Disk:master-sda",
            "selected": false,
            "service": "Hardware/IO"
        }, {
            "name": "Write.Operation",
            "resource_id": "5d26ca7f-3c61-324a-a9c2-2b6d57d6e1c5",
            "resource_name": "Ceph Cluster Id:27d39faa-48ae-4356-a8e3-19d5b81e179e",
            "selected": false,
            "service": "Service/Ceph"
        }, {
            "name": "Write.Sectors.Number",
            "resource_id": "f90af1c6-3dad-3f9c-9d0f-8a8d89420f4f",
            "resource_name": "PhysicalNode:master",
            "selected": false,
            "service": "Hardware/IO"
        }, {
            "name": "Write.Sectors.Number",
            "resource_id": "f9b44b21-8321-38a1-a1ae-860b8ff04c1f",
            "resource_name": "Disk:master-sda",
            "selected": false,
            "service": "Hardware/IO"
        }, {
            "name": "cpu",
            "resource_id": "0a8cb564-fa00-45c3-a8c8-195275308b45",
            "resource_name": "vm1",
            "selected": false,
            "service": "Service/Instance"
        }, {
            "name": "cpu",
            "resource_id": "73fb47c3-0790-4e98-b185-9a6e810320ad",
            "resource_name": "test-vnc-console-2",
            "selected": false,
            "service": "Service/Instance"
        }, {
            "name": "cpu",
            "resource_id": "d06a565a-60b1-41a1-8ba9-f34bccbc1d77",
            "resource_name": "test-vnc-console",
            "selected": false,
            "service": "Service/Instance"
        }, {
            "name": "cpu_util",
            "resource_id": "0a8cb564-fa00-45c3-a8c8-195275308b45",
            "resource_name": "vm1",
            "selected": false,
            "service": "Service/Instance"
        }, {
            "name": "cpu_util",
            "resource_id": "73fb47c3-0790-4e98-b185-9a6e810320ad",
            "resource_name": "test-vnc-console-2",
            "selected": false,
            "service": "Service/Instance"
        }, {
            "name": "cpu_util",
            "resource_id": "d06a565a-60b1-41a1-8ba9-f34bccbc1d77",
            "resource_name": "test-vnc-console",
            "selected": false,
            "service": "Service/Instance"
        }, {
            "name": "disk.ephemeral.size",
            "resource_id": "0a8cb564-fa00-45c3-a8c8-195275308b45",
            "resource_name": "vm1",
            "selected": false,
            "service": "Service/Instance"
        }, {
            "name": "disk.ephemeral.size",
            "resource_id": "426267c9-f1c5-46a3-a1a2-d1d8e2094b82",
            "resource_name": "vm1",
            "selected": false,
            "service": "Service/Instance"
        }, {
            "name": "disk.ephemeral.size",
            "resource_id": "73fb47c3-0790-4e98-b185-9a6e810320ad",
            "resource_name": "test-vnc-console-2",
            "selected": false,
            "service": "Service/Instance"
        }, {
            "name": "disk.ephemeral.size",
            "resource_id": "864df65b-d1cb-4c78-afb4-09b87340bdd3",
            "resource_name": "vm2",
            "selected": false,
            "service": "Service/Instance"
        }, {
            "name": "disk.ephemeral.size",
            "resource_id": "d06a565a-60b1-41a1-8ba9-f34bccbc1d77",
            "resource_name": "test-vnc-console",
            "selected": false,
            "service": "Service/Instance"
        }, {
            "name": "disk.read.bytes",
            "resource_id": "0a8cb564-fa00-45c3-a8c8-195275308b45",
            "resource_name": "vm1",
            "selected": false,
            "service": "Service/Instance"
        }, {
            "name": "disk.read.bytes",
            "resource_id": "73fb47c3-0790-4e98-b185-9a6e810320ad",
            "resource_name": "test-vnc-console-2",
            "selected": false,
            "service": "Service/Instance"
        }, {
            "name": "disk.read.bytes",
            "resource_id": "d06a565a-60b1-41a1-8ba9-f34bccbc1d77",
            "resource_name": "test-vnc-console",
            "selected": false,
            "service": "Service/Instance"
        }, {
            "name": "disk.read.requests",
            "resource_id": "0a8cb564-fa00-45c3-a8c8-195275308b45",
            "resource_name": "vm1",
            "selected": false,
            "service": "Service/Instance"
        }, {
            "name": "disk.read.requests",
            "resource_id": "73fb47c3-0790-4e98-b185-9a6e810320ad",
            "resource_name": "test-vnc-console-2",
            "selected": false,
            "service": "Service/Instance"
        }, {
            "name": "disk.read.requests",
            "resource_id": "d06a565a-60b1-41a1-8ba9-f34bccbc1d77",
            "resource_name": "test-vnc-console",
            "selected": false,
            "service": "Service/Instance"
        }, {
            "name": "disk.root.size",
            "resource_id": "0a8cb564-fa00-45c3-a8c8-195275308b45",
            "resource_name": "vm1",
            "selected": false,
            "service": "Service/Instance"
        }, {
            "name": "disk.root.size",
            "resource_id": "426267c9-f1c5-46a3-a1a2-d1d8e2094b82",
            "resource_name": "vm1",
            "selected": false,
            "service": "Service/Instance"
        }, {
            "name": "disk.root.size",
            "resource_id": "73fb47c3-0790-4e98-b185-9a6e810320ad",
            "resource_name": "test-vnc-console-2",
            "selected": false,
            "service": "Service/Instance"
        }, {
            "name": "disk.root.size",
            "resource_id": "864df65b-d1cb-4c78-afb4-09b87340bdd3",
            "resource_name": "vm2",
            "selected": false,
            "service": "Service/Instance"
        }, {
            "name": "disk.root.size",
            "resource_id": "d06a565a-60b1-41a1-8ba9-f34bccbc1d77",
            "resource_name": "test-vnc-console",
            "selected": false,
            "service": "Service/Instance"
        }, {
            "name": "disk.write.bytes",
            "resource_id": "0a8cb564-fa00-45c3-a8c8-195275308b45",
            "resource_name": "vm1",
            "selected": false,
            "service": "Service/Instance"
        }, {
            "name": "disk.write.bytes",
            "resource_id": "73fb47c3-0790-4e98-b185-9a6e810320ad",
            "resource_name": "test-vnc-console-2",
            "selected": false,
            "service": "Service/Instance"
        }, {
            "name": "disk.write.bytes",
            "resource_id": "d06a565a-60b1-41a1-8ba9-f34bccbc1d77",
            "resource_name": "test-vnc-console",
            "selected": false,
            "service": "Service/Instance"
        }, {
            "name": "disk.write.requests",
            "resource_id": "0a8cb564-fa00-45c3-a8c8-195275308b45",
            "resource_name": "vm1",
            "selected": false,
            "service": "Service/Instance"
        }, {
            "name": "disk.write.requests",
            "resource_id": "73fb47c3-0790-4e98-b185-9a6e810320ad",
            "resource_name": "test-vnc-console-2",
            "selected": false,
            "service": "Service/Instance"
        }, {
            "name": "disk.write.requests",
            "resource_id": "d06a565a-60b1-41a1-8ba9-f34bccbc1d77",
            "resource_name": "test-vnc-console",
            "selected": false,
            "service": "Service/Instance"
        }, {
            "name": "image",
            "resource_id": "beff4179-fe68-40d6-993b-8d072af1ccde",
            "resource_name": "uos-test-img",
            "selected": false,
            "service": "Service/Image"
        }, {
            "name": "image.size",
            "resource_id": "beff4179-fe68-40d6-993b-8d072af1ccde",
            "resource_name": "uos-test-img",
            "selected": false,
            "service": "Service/Image"
        }, {
            "name": "instance",
            "resource_id": "0a8cb564-fa00-45c3-a8c8-195275308b45",
            "resource_name": "vm1",
            "selected": false,
            "service": "Service/Instance"
        }, {
            "name": "instance",
            "resource_id": "426267c9-f1c5-46a3-a1a2-d1d8e2094b82",
            "resource_name": "vm1",
            "selected": false,
            "service": "Service/Instance"
        }, {
            "name": "instance",
            "resource_id": "73fb47c3-0790-4e98-b185-9a6e810320ad",
            "resource_name": "test-vnc-console-2",
            "selected": false,
            "service": "Service/Instance"
        }, {
            "name": "instance",
            "resource_id": "864df65b-d1cb-4c78-afb4-09b87340bdd3",
            "resource_name": "vm2",
            "selected": false,
            "service": "Service/Instance"
        }, {
            "name": "instance",
            "resource_id": "d06a565a-60b1-41a1-8ba9-f34bccbc1d77",
            "resource_name": "test-vnc-console",
            "selected": false,
            "service": "Service/Instance"
        }, {
            "name": "instance:m1.tiny",
            "resource_id": "0a8cb564-fa00-45c3-a8c8-195275308b45",
            "resource_name": "vm1",
            "selected": false,
            "service": "Service/Instance"
        }, {
            "name": "instance:m1.tiny",
            "resource_id": "426267c9-f1c5-46a3-a1a2-d1d8e2094b82",
            "resource_name": "vm1",
            "selected": false,
            "service": "Service/Instance"
        }, {
            "name": "instance:m1.tiny",
            "resource_id": "73fb47c3-0790-4e98-b185-9a6e810320ad",
            "resource_name": "test-vnc-console-2",
            "selected": false,
            "service": "Service/Instance"
        }, {
            "name": "instance:m1.tiny",
            "resource_id": "864df65b-d1cb-4c78-afb4-09b87340bdd3",
            "resource_name": "vm2",
            "selected": false,
            "service": "Service/Instance"
        }, {
            "name": "instance:m1.tiny",
            "resource_id": "d06a565a-60b1-41a1-8ba9-f34bccbc1d77",
            "resource_name": "test-vnc-console",
            "selected": false,
            "service": "Service/Instance"
        }, {
            "name": "memory",
            "resource_id": "0a8cb564-fa00-45c3-a8c8-195275308b45",
            "resource_name": "vm1",
            "selected": false,
            "service": "Service/Instance"
        }, {
            "name": "memory",
            "resource_id": "426267c9-f1c5-46a3-a1a2-d1d8e2094b82",
            "resource_name": "vm1",
            "selected": false,
            "service": "Service/Instance"
        }, {
            "name": "memory",
            "resource_id": "73fb47c3-0790-4e98-b185-9a6e810320ad",
            "resource_name": "test-vnc-console-2",
            "selected": false,
            "service": "Service/Instance"
        }, {
            "name": "memory",
            "resource_id": "864df65b-d1cb-4c78-afb4-09b87340bdd3",
            "resource_name": "vm2",
            "selected": false,
            "service": "Service/Instance"
        }, {
            "name": "memory",
            "resource_id": "d06a565a-60b1-41a1-8ba9-f34bccbc1d77",
            "resource_name": "test-vnc-console",
            "selected": false,
            "service": "Service/Instance"
        }, {
            "name": "network.incoming.bytes",
            "resource_id": "d06a565a-60b1-41a1-8ba9-f34bccbc1d77",
            "resource_name": "test-vnc-console",
            "selected": false,
            "service": "Service/Instance"
        }, {
            "name": "network.incoming.bytes",
            "resource_id": "nova-instance-instance-00000007-fa163e02b329",
            "resource_name": "vnet0",
            "selected": false,
            "service": "Service/Instance"
        }, {
            "name": "network.incoming.bytes",
            "resource_id": "nova-instance-instance-00000008-fa163e5c4fc8",
            "resource_name": "vnet1",
            "selected": false,
            "service": "Service/Instance"
        }, {
            "name": "network.incoming.bytes",
            "resource_id": "nova-instance-instance-00000009-fa163eecb229",
            "resource_name": "vnet1",
            "selected": false,
            "service": "Service/Instance"
        }, {
            "name": "network.incoming.packets",
            "resource_id": "d06a565a-60b1-41a1-8ba9-f34bccbc1d77",
            "resource_name": "test-vnc-console",
            "selected": false,
            "service": "Service/Instance"
        }, {
            "name": "network.incoming.packets",
            "resource_id": "nova-instance-instance-00000007-fa163e02b329",
            "resource_name": "vnet0",
            "selected": false,
            "service": "Service/Instance"
        }, {
            "name": "network.incoming.packets",
            "resource_id": "nova-instance-instance-00000008-fa163e5c4fc8",
            "resource_name": "vnet1",
            "selected": false,
            "service": "Service/Instance"
        }, {
            "name": "network.incoming.packets",
            "resource_id": "nova-instance-instance-00000009-fa163eecb229",
            "resource_name": "vnet1",
            "selected": false,
            "service": "Service/Instance"
        }, {
            "name": "network.incoming.total.bytes",
            "resource_id": "0a8cb564-fa00-45c3-a8c8-195275308b45",
            "resource_name": "vm1",
            "selected": false,
            "service": "Service/Instance"
        }, {
            "name": "network.incoming.total.bytes",
            "resource_id": "73fb47c3-0790-4e98-b185-9a6e810320ad",
            "resource_name": "test-vnc-console-2",
            "selected": false,
            "service": "Service/Instance"
        }, {
            "name": "network.incoming.total.bytes",
            "resource_id": "d06a565a-60b1-41a1-8ba9-f34bccbc1d77",
            "resource_name": "test-vnc-console",
            "selected": false,
            "service": "Service/Instance"
        }, {
            "name": "network.outgoing.bytes",
            "resource_id": "d06a565a-60b1-41a1-8ba9-f34bccbc1d77",
            "resource_name": "test-vnc-console",
            "selected": false,
            "service": "Service/Instance"
        }, {
            "name": "network.outgoing.bytes",
            "resource_id": "nova-instance-instance-00000007-fa163e02b329",
            "resource_name": "vnet0",
            "selected": false,
            "service": "Service/Instance"
        }, {
            "name": "network.outgoing.bytes",
            "resource_id": "nova-instance-instance-00000008-fa163e5c4fc8",
            "resource_name": "vnet1",
            "selected": false,
            "service": "Service/Instance"
        }, {
            "name": "network.outgoing.bytes",
            "resource_id": "nova-instance-instance-00000009-fa163eecb229",
            "resource_name": "vnet1",
            "selected": false,
            "service": "Service/Instance"
        }, {
            "name": "network.outgoing.packets",
            "resource_id": "d06a565a-60b1-41a1-8ba9-f34bccbc1d77",
            "resource_name": "test-vnc-console",
            "selected": false,
            "service": "Service/Instance"
        }, {
            "name": "network.outgoing.packets",
            "resource_id": "nova-instance-instance-00000007-fa163e02b329",
            "resource_name": "vnet0",
            "selected": false,
            "service": "Service/Instance"
        }, {
            "name": "network.outgoing.packets",
            "resource_id": "nova-instance-instance-00000008-fa163e5c4fc8",
            "resource_name": "vnet1",
            "selected": false,
            "service": "Service/Instance"
        }, {
            "name": "network.outgoing.packets",
            "resource_id": "nova-instance-instance-00000009-fa163eecb229",
            "resource_name": "vnet1",
            "selected": false,
            "service": "Service/Instance"
        }, {
            "name": "network.outgoing.total.bytes",
            "resource_id": "0a8cb564-fa00-45c3-a8c8-195275308b45",
            "resource_name": "vm1",
            "selected": false,
            "service": "Service/Instance"
        }, {
            "name": "network.outgoing.total.bytes",
            "resource_id": "73fb47c3-0790-4e98-b185-9a6e810320ad",
            "resource_name": "test-vnc-console-2",
            "selected": false,
            "service": "Service/Instance"
        }, {
            "name": "network.outgoing.total.bytes",
            "resource_id": "d06a565a-60b1-41a1-8ba9-f34bccbc1d77",
            "resource_name": "test-vnc-console",
            "selected": false,
            "service": "Service/Instance"
        }, {
            "name": "storage.objects",
            "resource_id": "956d54a37b8449ff92d5796cb8866465",
            "resource_name": "UNKONWN",
            "selected": false,
            "service": "Service/ObjectStorage"
        }, {
            "name": "storage.objects",
            "resource_id": "e3f0f391ed3547368bd0331d1f79f255",
            "resource_name": "UNKONWN",
            "selected": false,
            "service": "Service/ObjectStorage"
        }, {
            "name": "storage.objects.containers",
            "resource_id": "956d54a37b8449ff92d5796cb8866465",
            "resource_name": "UNKONWN",
            "selected": false,
            "service": "Service/ObjectStorage"
        }, {
            "name": "storage.objects.containers",
            "resource_id": "e3f0f391ed3547368bd0331d1f79f255",
            "resource_name": "UNKONWN",
            "selected": false,
            "service": "Service/ObjectStorage"
        }, {
            "name": "storage.objects.size",
            "resource_id": "956d54a37b8449ff92d5796cb8866465",
            "resource_name": "UNKONWN",
            "selected": false,
            "service": "Service/ObjectStorage"
        }, {
            "name": "storage.objects.size",
            "resource_id": "e3f0f391ed3547368bd0331d1f79f255",
            "resource_name": "UNKONWN",
            "selected": false,
            "service": "Service/ObjectStorage"
        }, {
            "name": "vcpus",
            "resource_id": "0a8cb564-fa00-45c3-a8c8-195275308b45",
            "resource_name": "vm1",
            "selected": false,
            "service": "Service/Instance"
        }, {
            "name": "vcpus",
            "resource_id": "426267c9-f1c5-46a3-a1a2-d1d8e2094b82",
            "resource_name": "vm1",
            "selected": false,
            "service": "Service/Instance"
        }, {
            "name": "vcpus",
            "resource_id": "73fb47c3-0790-4e98-b185-9a6e810320ad",
            "resource_name": "test-vnc-console-2",
            "selected": false,
            "service": "Service/Instance"
        }, {
            "name": "vcpus",
            "resource_id": "864df65b-d1cb-4c78-afb4-09b87340bdd3",
            "resource_name": "vm2",
            "selected": false,
            "service": "Service/Instance"
        }, {
            "name": "vcpus",
            "resource_id": "d06a565a-60b1-41a1-8ba9-f34bccbc1d77",
            "resource_name": "test-vnc-console",
            "selected": false,
            "service": "Service/Instance"
        }, {
            "name": "volume",
            "resource_id": "56d01235-0483-4bb0-8519-174ac20be059",
            "resource_name": "vol-1",
            "selected": false,
            "service": "Service/BlockStorage"
        }, {
            "name": "volume.size",
            "resource_id": "56d01235-0483-4bb0-8519-174ac20be059",
            "resource_name": "vol-1",
            "selected": false,
            "service": "Service/BlockStorage"
        }]
})